# Generated by Django 5.1.3 on 2024-11-14 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editor", "0002_alter_document_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="owner",
        ),
        migrations.AddField(
            model_name="document",
            name="collaborators",
            field=models.ManyToManyField(
                related_name="documents", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
