# Generated by Django 4.2.5 on 2024-12-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editor", "0005_documentversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversion",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
