# Generated by Django 4.2.5 on 2024-12-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editor", "0006_documentversion_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="edit_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="suggested_edit",
            field=models.TextField(blank=True, null=True),
        ),
    ]
